pg:
  image: library/postgres:latest
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_DATABASE=phoenix_trello_dev
phoenix-trello:
  image: letusfly85/phoenix-trello:latest
  links:
    - "pg:postgresql"
  ports:
    - "8000:80"
  environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_DATABASE=phoenix_trello_dev
